B-tagging WP SFs and systematics
TopEFT/topcoffea pull request #213
Opened 2022-03-30 17:06 UTC by andrea21z

Changes:
- I have included the WP loose in the implematation of the b-tagging SFs method (following the [recommendations](https://twiki.cern.ch/twiki/bin/viewauth/CMS/BTagSFMethods)).
- Before we had only two syst. variations (btagSFUp and btagSFDown), and now they are splited by flavor (bc or light) and by correlated/uncorrelated:
        - btagSFbc_corrUp/Down
        - btagSFlight_corrUp/Down
        - btagSFbc_uncorrUp/Down
        - btagSFlight_uncorrUp/Down

I have checked the Data/MC agreement in the ttbar CR and the syst. variations and everything looks fine!

2022-03-30 17:10 UTC, bryates requested changes
Thanks @andrea21z, I just had one change. I'll update the datacard to handle the correlations, but we don't need to hold off on this PR.

2022-03-30 17:10 UTC, bryates commented on analysis/topEFT/topeft.py
> +        '''
Can you remove the block comments here?

2022-03-31 09:10 UTC, andrea21z commented on analysis/topEFT/topeft.py
> +        '''
yes, I  forget to uncomment it

2022-03-31 13:00 UTC, bryates approved these changes
Looks good!

2022-03-31 13:10 UTC, andrea21z commented
> @andrea21z looks like the datacard checks are failing. Do we expect these updates to affect the nominal yields?

Yes, they will change a little

2022-03-31 13:12 UTC, bryates commented
> > @andrea21z looks like the datacard checks are failing. Do we expect these updates to affect the nominal yields?
> 
> Yes, they will change a little

Ok, then can you update the reference files? Once that is done, I think this PR should be ready to merge.

2022-03-31 13:23 UTC, bryates commented
> > > > @andrea21z looks like the datacard checks are failing. Do we expect these updates to affect the nominal yields?
> > > 
> > > 
> > > Yes, they will change a little
> > 
> > 
> > Ok, then can you update the reference files? Once that is done, I think this PR should be ready to merge.
> 
> I have updated the reference json file, but I think I can't update the datacard files, those files were always updated by Kelci or you because I can't run those tests in Oviedo (or maybe other reason, I don't remember...)

Ok, I can't remember either, but I'll take care of it now.

2022-03-31 13:36 UTC, andrea21z commented
> > > > > @andrea21z looks like the datacard checks are failing. Do we expect these updates to affect the nominal yields?
> > > > 
> > > > 
> > > > Yes, they will change a little
> > > 
> > > 
> > > Ok, then can you update the reference files? Once that is done, I think this PR should be ready to merge.
> > 
> > 
> > I have updated the reference json file, but I think I can't update the datacard files, those files were always updated by Kelci or you because I can't run those tests in Oviedo (or maybe other reason, I don't remember...)
> 
> Ok, I can't remember either, but I'll take care of it now.

Thank you very much :)

2022-04-01 03:44 UTC, kmohrman commented
Thanks @andrea21z, this PR looks good to me. I just pushed two small commits:
* Update ref yields (the ones for the larger check than the CI check)
* Revert remorm/fact stuff to match the master branch (we do not include renorm and fact right now, and instead just use renormfact since we're not currently doing the envelope approach)

2022-04-01 14:39 UTC, merged